# Generated by Django 5.2 on 2025-05-04 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaredapp', '0002_item_activo_item_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('CONCRETADA', 'Concretada')], default='PENDIENTE', max_length=20)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiario_solicitudes', to=settings.AUTH_USER_MODEL)),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donante_solicitudes', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_solicitudes', to='donaredapp.item')),
            ],
            options={
                'unique_together': {('item', 'beneficiario')},
            },
        ),
    ]
