# Generated by Django 5.2 on 2025-05-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaredapp', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
