# Generated by Django 5.2 on 2025-05-23 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaredapp', '0006_profile_validado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='movil',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El número debe tener entre 10 y 20 dígitos. Puede incluir +, espacios y guiones.', regex='^\\+?[0-9\\s\\-]{10,20}$')]),
        ),
    ]
