# Generated by Django 5.2 on 2025-05-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaredapp', '0007_alter_profile_movil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='movil',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
