# Generated by Django 5.2 on 2025-05-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaredapp', '0008_alter_profile_movil'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='domicilio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
