# Generated by Django 5.2.1 on 2025-05-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaredapp', '0010_item_latitude_item_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='zona',
        ),
    ]
