# Generated by Django 5.2.1 on 2025-05-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaredapp', '0011_remove_item_zona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zona',
        ),
    ]
