# Generated by Django 5.2 on 2025-06-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaredapp', '0012_delete_zona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Donación', 'verbose_name_plural': 'Donaciones'},
        ),
    ]
