# Generated by Django 5.2 on 2025-06-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaredapp', '0013_alter_solicitud_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagen',
            field=models.ImageField(blank=True, default='sin_imagen.png', null=True, upload_to='items/'),
        ),
    ]
