# Generated by Django 5.2.1 on 2025-06-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaredapp', '0015_alter_item_imagen_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='estado',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', help_text='Estado de la reseña', max_length=10),
        ),
    ]
