# Generated by Django 5.2 on 2025-06-10 15:03

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaredapp', '0015_alter_item_descripcion_alter_item_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='movil',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='AR'),
        ),
    ]
