# Generated by Django 5.2.1 on 2025-06-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donaredapp', '0016_resena_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resena',
            name='destacada',
        ),
    ]
