# Generated by Django 5.2.1 on 2025-06-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaredapp', '0017_resena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='activo',
        ),
        migrations.AddField(
            model_name='item',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('eliminado', 'Eliminado')], default='activo', max_length=10),
        ),
    ]
