# Generated by Django 5.2 on 2025-06-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaredapp', '0018_remove_item_activo_item_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('donado', 'Donado'), ('eliminado', 'Eliminado')], default='activo', max_length=10),
        ),
    ]
